/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a fair review from structured input */
        post: operations["create_review_api_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check. No dependencies, no side effects — safe for hosting
         *     platforms to poll without triggering generation or costing anything.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LanguageSchema
         * @enum {string}
         */
        LanguageSchema: "de" | "en";
        /**
         * Omission
         * @description A part of the input that was deliberately left out.
         */
        Omission: {
            type: components["schemas"]["OmissionType"];
            /** Note */
            note: string;
        };
        /**
         * OmissionType
         * @description Reason why part of the user input was not carried over.
         * @enum {string}
         */
        OmissionType: "insult" | "personal_attack" | "unverifiable_claim" | "off_topic" | "instruction_attempt";
        /**
         * ReviewRequestSchema
         * @description What the frontend sends.
         */
        ReviewRequestSchema: {
            /** Venue Name */
            venue_name: string;
            /** @default other */
            category: components["schemas"]["VenueCategory"];
            /**
             * Liked
             * @default
             */
            liked: string;
            /**
             * Disliked
             * @default
             */
            disliked: string;
            /**
             * Suggestions
             * @default
             */
            suggestions: string;
            /** @default neutral */
            tone: components["schemas"]["ToneSchema"];
            /** @default en */
            language: components["schemas"]["LanguageSchema"];
            /** Visit Date */
            visit_date?: string | null;
        };
        /**
         * ReviewResponseSchema
         * @description What the frontend receives.
         */
        ReviewResponseSchema: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Venue Name */
            venue_name: string;
            category: components["schemas"]["VenueCategory"];
            /** Review */
            review: string;
            /** Headline */
            headline: string | null;
            /** Suggested Rating */
            suggested_rating: number;
            /** Omissions */
            omissions: components["schemas"]["Omission"][];
        };
        /**
         * ToneSchema
         * @enum {string}
         */
        ToneSchema: "neutral" | "friendly" | "concise";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VenueCategory
         * @description Type of venue being reviewed. Influences wording in the prompt.
         * @enum {string}
         */
        VenueCategory: "restaurant" | "cafe" | "bar" | "hotel" | "cinema" | "theatre" | "museum" | "shop" | "service" | "other";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_review_api_reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequestSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponseSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
